name: cycles
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.*
  - cmake
  - make
  - ninja
  - c-compiler
  - cxx-compiler
  - doxygen
  - sdl2
  - sdl2_ttf
  - sdl2_gfx
  - pkg-config
  - pip 
  - pip:
    - breathe==4.35.0
    - sphinx==7.4.7
    - sphinx_rtd_theme==2.0.0
